name: minigym
description: A record exercise project.
publish_to: 'none'

version: 1.0.0+1

environment:
    sdk: '>=2.19.0 <3.0.0'

dependencies:
    flutter:
        sdk: flutter
    flutter_localizations:
        sdk: flutter

    # ui(icon, font...)
    cupertino_icons: ^1.0.2
    font_awesome_flutter: ^10.3.0
    google_fonts: ^4.0.1
    table_calendar: ^3.0.8

    # firebase
    firebase_core: ^2.5.0
    firebase_auth: ^4.2.2
    cloud_firestore: ^4.3.2
    firebase_storage: ^11.0.14

    # localization
    intl: ^0.17.0

    # router
    go_router: 6.0.2

    # local data persist
    shared_preferences: ^2.0.18

    # state management
    provider: 6.0.5
    flutter_riverpod: ^2.1.3

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    generate: true
    uses-material-design: true
flutter_intl:
    enabled: true
